apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: genopredict

resources:
  - namespace.yaml
  - persistent-volumes.yaml
  - configmap-prometheus.yaml
  - configmap-grafana.yaml
  - secret-grafana.yaml
  - mlflow.yaml
  - api.yaml
  - frontend.yaml
  - drift-monitor.yaml
  - prometheus.yaml
  - grafana.yaml
  - ingress.yaml

images:
  - name: genopredict-api
    newName: ghcr.io/badreddine-chihab/genopredict-api
    newTag: latest
  - name: genopredict-frontend
    newName: ghcr.io/badreddine-chihab/genopredict-frontend
    newTag: latest
  - name: genopredict-mlflow
    newName: ghcr.io/badreddine-chihab/genopredict-mlflow
    newTag: latest
