stages:
  download_clinvar:
    cmd: python3 src/data/download_clinvar.py
    deps:
      - src/data/download_clinvar.py
    outs:
      - data/raw/clinvar.vcf.gz

  process_clinvar:
    cmd: python3 src/features/process_clinvar.py
    deps:
      - src/features/process_clinvar.py
      - data/raw/clinvar.vcf.gz
    outs:
      - data/processed/clinvar_cleaned.csv

  clean_labels:
    cmd: python3 src/features/clean_labels.py
    deps:
      - src/features/clean_labels.py
      - data/processed/clinvar_cleaned.csv
    outs:
      - data/processed/training_base.csv
      - data/processed/vus_to_predict.csv

  download_dbsnp:
    cmd: python3 src/data/download_dbsnp.py
    deps:
      - src/data/download_dbsnp.py
    outs:
      - data/raw/dbsnp_common.vcf.gz

  process_dbsnp:
    cmd: python3 src/features/process_dbsnp.py
    deps:
      - src/features/process_dbsnp.py
      - data/raw/dbsnp_common.vcf.gz
    outs:
      - data/processed/dbsnp_frequencies.csv

  merge_datasets:
    cmd: python3 src/features/merge_datasets.py
    deps:
      - src/features/merge_datasets.py
      - data/processed/training_base.csv
      - data/processed/dbsnp_frequencies.csv
    outs:
      - data/processed/final_training_dataset.csv

  encode_features:
    cmd: python3 src/features/encode_features.py
    deps:
      - src/features/encode_features.py
      - data/processed/final_training_dataset.csv
    outs:
      - data/processed/encoded_training_dataset.csv