apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: genopredict-dev

resources:
  - ../../base

patches:
  - path: ingress-hosts.yaml
  - path: resource-requests.yaml

secretGenerator:
  - name: grafana-admin
    behavior: replace
    literals:
      - admin-user=admin
      - admin-password=change-me-dev

generatorOptions:
  disableNameSuffixHash: true
